clear; clc

% "example_file.xls" should contain the coordinates of ROIs where
% columns are x y & z coordinates (MNI) of ROI centroids

coord = xlsread('/coordinates/CombinedROICoordinates.xls'); %put your filename here
% coord = Rx3 matrix where R is number of ROIs and columns are x y & z coordinates (MNI) of ROI centroids

radius = 5; % radius in mm
voxel_size = 2; % 2x2x2 mm3 (matrix size 91x109x91)
% voxel_size = 3; % 3x3x3 mm3 (matrix size 61x73x61)

% NOTE: Please verify the transformation matrix for your data at--
% \marsbar-0.43\@maroi\private\my_classdata.m

get_marsbar_rois(coord,radius,voxel_size)
clc

% Outputs:
% nii files for each ROI are saved in "niisave" folder. They are numbered based on ROI indices in coord variable
% Combined image of all ROIs combined is saved as "all_ROIs_combined.nii"
% Mat files generated by Marsbar are saved in "spheres_marsbar_mat" folder (used to create the nii files)

%%